name: bars
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.8+35

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^5.0.2
  firebase_core: ^2.27.0
  # firebase_analytics: ^8.1.1
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.5
  provider: ^6.0.3
  # another_flushbar: ^1.10.23
  image_picker: ^0.8.4+2
  firebase_storage: ^11.6.9
  flutter_image_compress: ^2.0.4
  path_provider: ^2.0.2
  uuid: ^3.0.4
  cached_network_image: ^3.1.0-alpha.1
  image_cropper: ^1.4.0
  # flutter_slidable: ^1.3.0
  shimmer: ^2.0.0
  # animator: ^3.2.0
  intl: ^0.17.0
  # random_color: ^1.0.6-nullsafety
  # flutter_launcher_icons: ^0.9.0
  webview_flutter: ^3.0.4
  url_launcher: ^6.0.6
  flutter_native_splash: ^2.3.6
  # bloc: ^7.0.0
  avatar_glow: ^2.0.1
  # flutter_bloc: ^7.0.1 
  # equatable: ^2.0.2
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^9.1.5
  # rxdart: ^0.27.1
  share: ^2.0.4
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.6
  # flutter_offline: "^2.0.0"
  connectivity_plus: ^5.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  timeago: ^3.0.2
  focused_menu: ^1.0.5
  email_validator: ^2.0.1
  geolocator: ^8.0.5
  geocoding: ^2.2.0
  http: ^1.1.0
  maps_launcher: ^2.0.0
  animated_text_kit: ^4.2.1
  palette_generator: ^0.3.3+1
  flutter_blurhash: ^0.8.0
  blurhash: ^1.1.1
  store_redirect: ^2.0.1
  # syncfusion_flutter_calendar: ^20.2.48
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0
  # percent_indicator: ^4.2.2
  firebase_dynamic_links: ^5.0.1
  animations: ^2.0.7
  firebase_app_check: ^0.2.2+7
  # async: ^2.7.0
  currency_picker: ^2.0.12
  # pay: ^1.1.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  table_calendar: ^3.0.8
  # flutter_paystack: ^1.0.7
  google_maps_flutter: ^2.6.0
  google_generative_ai: ^0.4.3
  photo_view: ^0.14.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.1
  cloud_functions: ^4.0.0
  vibration: ^1.7.5
  firebase_analytics: ^10.8.9
  flutter_markdown: ^0.7.3+1
  # app_tracking_transparency: ^2.0.4


  # ade_flutterwave_working_version: ^0.0.2+2

  # chewie: ^1.4.0
  # flutter_stripe: ^9.2.0


  # video_player: ^2.4.7

  # flutter_paystack: ^1.0.7
 
  json_annotation: any
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/barsLauncher.png"

flutter_native_splash:
  image: assets/images/barsw.png
  color: "1a1a1a"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # build_runner: ^2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bessita
      fonts:
        - asset: assets/fonts/Bessita.otf
    # - family: Montserrat
    #   fonts:
    #     - asset: assets/fonts/Montserrat-Regular.ttf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

